num_examples=np.genfromtxt('randomnumbers.txt')
D_examples = np.zeros(10)
for i in range(10):
    D_examples[i],_ = stats.kstest(num_examples[:,i],'norm')
plt.figure()
plt.scatter(range(10),D_examples, label='examples')
plt.scatter(11,D_sci[-1],label = 'mine')
plt.legend(loc='best')
plt.xlabel('set number')
plt.ylabel('D max')
plt.title('KS-test w.r.t Gaussian of 10 examples and my random number')
#plt.savefig('1d.png')
plt.show()
print('from the figure, we can see that my random number has a lower D value of KS-test compared to the examples.')